apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-primary-config
data:
  config.hcl: | 
    storage "raft" {
      path    = "./vault/data"
      node_id = "node1"
    }

    listener "tcp" {
      address     = "0.0.0.0:8201"
      tls_disable = "true"
    }

    api_addr = "http://vault-primary-service:8201"
    cluster_addr = "http://vault-primary-service-cluster:8202"
    ui = true
    disable_mlock = true

    license_path = "/vault/vault.hclic"

    log_level = "trace"