apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-pr-config
data:
  config.hcl: | 
    storage "raft" {
      path    = "./vault/data"
      node_id = "pr"
    }

    listener "tcp" {
      address     = "0.0.0.0:8203"
      tls_disable = "true"
    }

    api_addr = "http://vault-pr-service:8203"
    cluster_addr = "http://vault-pr-service-cluster:8204"
    ui = true
    disable_mlock = true

    license_path = "/vault/vault.hclic"

    log_level = "trace"