apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-pr-config
data:
  config.hcl: | 
    storage "raft" {
      path    = "./vault/data"
      node_id = "pr"
    }

    listener "tcp" {
      address     = "0.0.0.0:8202"
      tls_disable = "true"
    }

    api_addr = "http://127.0.0.1:8202"
    cluster_addr = "http://vault-pr-service:8202"
    ui = true
    disable_mlock = true

    license_path = "/vault/vault.hclic"