apiVersion: v1
kind: Pod
metadata:
  name: vault-pr
spec:
  initContainers:
  - name: create-vault-data-dir
    image: busybox
    command: ["mkdir", "-p", "/vault/data"]
    volumeMounts:
    - name: vault-data
      mountPath: /vault/data
  containers:
  - name: vault
    image: hashicorp/vault-enterprise
    command: ["vault", "server", "-config=/vault/config/config.hcl"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1"
      limits:
        memory: "2048Mi"
        cpu: "2"
    ports:
    - containerPort: 8202
      hostPort: 8202
    volumeMounts:
    - name: config-volume
      mountPath: /vault/config/config.hcl
      subPath: config.hcl
    - name: vault-data
      mountPath: /vault/data
    - name: license-volume
      mountPath: /vault/vault.hclic
      subPath: vault.hclic
  volumes:
  - name: config-volume
    configMap:
      name: vault-pr-config
  - name: license-volume
    secret:
      secretName: vault-license
  - name: vault-data
    emptyDir: {}